<head>
    <link rel="shortcut icon" href="favicon.ico" />
    <meta http-equiv="CONTENT-TYPE" content="text/html" charset="utf-8">
    <title>{{ app_name }}</title>
    <meta name="description" content="utilities for blockchain systems integration">
    <meta name="keywords" content="blocktool">
    <style>
        body { font-family: Arial, "Times New Roman", Georgia, Serif;}
    </style>
</head>
